### ISSUE TITLE
Is there any method to conver server-handlers to scheme documents ?

### ISSUE THREAD

**Issue by zhaosiwen1949** [open-rpc/server-js#211]
Hi, I have been concerned about OpenRPC, and trying to use it in my project, so there's a question: How can I conver server-handlers method in my TS file to scheme documents ?

**Comment by shanejonas** [comment]
Hi, thanks for your interest in OpenRPC.

As of right now you cannot generate an openrpc document from the methods you wrote in typescript, just the other way around, generate types from the openrpc document.

If you wanted to implement this feature, you could make a pull request or maybe a new tool that generates it from decorators: http://www.typescriptlang.org/docs/handbook/decorators.html

**Comment by shanejonas** [comment]
the flow we use now is write the openrpc document and then https://github.com/open-rpc/typings to generate the type definitions to include in server-js or any other project

**Comment by zhaosiwen1949** [comment]
Thanks for your advice :)

**Comment by BelfordZ** [comment]
hope this has helped. Let us know if you have more details about your issue. Thanks.
